### ISSUE TITLE
Typing error in Link in the YT-Video

### ISSUE THREAD

**Issue by Medizinmann-MD** [chris1111/Legacy-Duet-OpenCore-Packager#1]
The link in the YT-Video leads to a 404 as it is missing 2 characters "er".

**Comment by chris1111** [comment]
> The link in the YT-Video leads to a 404 as it is missing 2 characters "er".

Vidéo link works

**Comment by Medizinmann-MD** [comment]
> > The link in the YT-Video leads to a 404 as it is missing 2 characters "er".
> 
> Vidéo link works

Here is a misunderstanding - the link to this github in the YT-Video is missing the "er"

I would have commented on YT - but comments there are deactivated.
